### ISSUE TITLE
Exercise 9 of 13 can't be solved; problem with paths in equality check

### ISSUE THREAD

**Issue by davidhatten** [stevekane/promise-it-wont-hurt#92]
So I have a working solution for Exercise 9 (Throw an error) and most of the output lines are equal, but anything containing a path is a problem. The app seems to be generating paths from `/home/<user>/.nvm/versions/node/<version>/lib/node_modules/promise-it-wont-hurt/exercises/throw_an_error/solution/solution.js` whereas the execution returns the path `/home/<user>/code/nodeLearning/nodePromise/program.js` because that's the file I'm running.

Am I messing something obvious here? I am using NVM, for what it's worth.

**Comment by HermantNET** [comment]
Same problem, my dev environments on a different drive so maybe that has something to do with it? Everything lines up except for the paths.

**Comment by rossb** [comment]
Same issue here on OS X 10.11.5 (although in my case the error compares the path of my file with `/usr/local/lib/node_modules/…`, where my node modules live).

**Comment by rossb** [comment]
Just a note to say I see the issue as above verifying lesson 10 of 13.

**Comment by kvsm** [comment]
Same error here.

**Comment by donovanh** [comment]
A simple fix in this PR https://github.com/stevekane/promise-it-wont-hurt/pull/106

**Comment by gness1804** [comment]
I am still having this problem, even after implementing the fix from #106. I have a working solution but keep getting the following error: 

` "SyntaxError: Unexpected token o in JSON at position 1" ==    "SyntaxError: Unexpected token o in JSON at position 1"
   "    at Object.parse (native)"      ==    "    at Object.parse (native)"
   "    at /Users/[my-file-path]/exer-9.js:4:20" !=    "    at /usr/local/lib/node_modules/promise-it-wont-hurt/exercises/throw_an_error/solution/solution.js:6:20"
   "    at parsePromised (/Users/[my-file-path]/exer-9.js:2:10)" !=    "    at parsePromised (/usr/local/lib/node_modules/promise-it-wont-hurt/exercises/throw_an_error/solution/solution.js:4:10)"
   "    at Object.<anonymous> (/Users/[my-file-path]/exer-9.js:12:1)" !=    "    at Object.<anonymous> (/usr/local/lib/node_modules/promise-it-wont-hurt/exercises/throw_an_error/solution/solution.js:13:1)"
   "    at Module._compile (module.js:541:32)" ==    "    at Module._compile (module.js:541:32)"
   "    at Object.Module._extensions..js (module.js:550:10)" ==    "    at Object.Module._extensions..js (module.js:550:10)"
   "    at Module.load (module.js:458:32)" ==    "    at Module.load (module.js:458:32)"
   "    at tryModuleLoad (module.js:417:12)" ==    "    at tryModuleLoad (module.js:417:12)"
   "    at Function.Module._load (module.js:409:3)" ==    "    at Function.Module._load (module.js:409:3)"
   "    at Module.runMain (module.js:575:10)" ==    "    at Module.runMain (module.js:575:10)"
   ""                                  ==    ""
   
   ✗ Submission results did not match expected!

# FAIL

Your solution to Throw an error didn't pass. Try again!`

My code : 

`function parsePromised (json) {
  return new Promise(function (fulfill, reject) {
    try {
      fulfill(JSON.parse(json));
    }
    catch(e) {
    reject(e.message);
    }
  });
};

parsePromised(process.argv[2]).then(null, console.log);`

I've tried the `catch` statement with `e` and `e.message` (as above), but it still errors out. The issue seems to be with the file path, not with the logic. Am I missing something?

**Comment by qyearsley** [comment]
I also ran into this, and there are already proposed PRs to fix this issue... @stevekane could you merge a fix?

**Comment by addaleax** [comment]
I think this has been fixed now, so I’m closing this. Please feel free to re-open if you run into any more trouble!v
